### ISSUE TITLE
No mention of host-meta which can be used to redirect webfinger requests

### ISSUE THREAD

**Issue by ThisIsMissEm** [swicg/activitypub-webfinger#28]
For example, the user `@strangeparts@strangeparts.com` does not respond to webfinger requests on `strangeparts.com` but does respond to `https://strangeparts.com/.well-known/host-meta` which redirects to `https://mastodon.strangeparts.com/.well-known/host-meta` which gives the templated URI for webfinger requests: `https://mastodon.strangeparts.com/.well-known/webfinger?resource={uri}`

Looks like some are using this host-meta redirect to use a custom domain for actors which is different to the actual domain of the server.

**Comment by trwnh** [comment]
Oh, hm, I think the expectation is that (at least in Mastodon) you need to redirect the `/.well-known/webfinger` endpoint entirely, not that you use `/.well-known/host-meta` or `/.well-known/host-meta.json`. https://docs.joinmastodon.org/admin/config/#web_domain calls this out:

> To install Mastodon on `mastodon.example.com` in such a way it can serve `@alice@example.com`, set LOCAL_DOMAIN to `example.com` and WEB_DOMAIN to `mastodon.example.com`. This also requires additional configuration on the server hosting example.com to redirect requests from `https://example.com/.well-known/webfinger` to `https://mastodon.example.com/.well-known/webfinger`. For instance, with nginx, the configuration could look like the following:
> 
> ```
> location /.well-known/webfinger {
> add_header Access-Control-Allow-Origin '*';
> return 301 https://mastodon.example.com$request_uri;
> }
> ```

The use of host-meta as a "second layer of indirection" is something that mostly a holdover from the OStatus days, IIRC. Most projects that aren't Mastodon or Pleroma will not check host-meta at all, and will instead always skip straight to the `/.well-known/webfinger` endpoint. I don't think it makes sense to unnecessarily pressure everyone into adopting host-meta or supporting variable LRDD endpoints, where WebFinger is in fact a profile of LRDD that serves specifically JRD instead of XRD. (Another interesting thing most people aren't aware of is that projects like Pleroma respond to most browsers' default Accept headers with an XRD response to `/.well-known/webfinger`, since that route used to pull double duty back in the day! See https://git.pleroma.social/pleroma/pleroma/-/issues/3254 for more details.)

**Comment by ThisIsMissEm** [comment]
I think maybe it'd be worth having as a non-normative section? I absolutely didn't know host-meta was a thing until I was trying to help someone debug why webfinger requests were failing.

**Comment by trwnh** [comment]
My concern is that for how the Fediverse uses WebFinger, no one should have to know about host-meta. Looking for a link with rel=lrdd is not something that anyone should generally have to do, because the Fediverse doesn't use LRDD. It uses WebFinger directly. The correct solution is to redirect to the appropriate WebFinger endpoint.

With that said, this doesn't seem to be explicitly called out as a consideration; it's only alluded to by Example 4 showing an HTTP 307 Temporary Redirect from `example.com`'s endpoint to `activitypub.example.com`'s endpoint. Most likely, we can add some language to Section 2.1 "Forward discovery" to explicitly say that redirects can happen, and that redirects should be followed.
